[2023-12-09 16:27:14,967] ERROR log_exception() L1449 Exception on /dataset/upload [POST] - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "C:\Users\biaoz\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\biaoz\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\biaoz\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
  File "C:\Users\biaoz\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
[2023-12-09 16:27:14,977] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 16:27:14] "[35m[1mPOST /dataset/upload HTTP/1.1[0m" 500 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 16:27:28,483] INFO _log() L224   * Running on http://127.0.0.1:5000 (Press CTRL+C to quit) - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 16:27:37,676] ERROR log_exception() L1449 Exception on /dataset/upload [POST] - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "C:\Users\biaoz\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\biaoz\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\biaoz\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
  File "C:\Users\biaoz\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
[2023-12-09 16:27:37,681] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 16:27:37] "[35m[1mPOST /dataset/upload HTTP/1.1[0m" 500 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 16:27:54,328] INFO _log() L224   * Running on http://127.0.0.1:5000 (Press CTRL+C to quit) - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 16:27:56,701] ERROR log_exception() L1449 Exception on /dataset/upload [POST] - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "C:\Users\biaoz\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\biaoz\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\biaoz\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
  File "C:\Users\biaoz\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
[2023-12-09 16:27:56,706] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 16:27:56] "[35m[1mPOST /dataset/upload HTTP/1.1[0m" 500 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 16:28:26,021] INFO _log() L224   * Running on http://127.0.0.1:5000 (Press CTRL+C to quit) - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 16:28:30,506] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 16:28:30] "POST /dataset/upload HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 16:39:18,166] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 16:39:18] "POST /dataset/upload HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 16:42:46,057] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 16:42:46] "POST /dataset/upload HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 16:50:59,617] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 16:50:59] "POST /dataset/upload HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 16:55:54,263] INFO _log() L224   * Running on http://127.0.0.1:5000 (Press CTRL+C to quit) - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 16:55:59,466] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 16:55:59] "POST /dataset/upload HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 16:56:08,655] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 16:56:08] "POST /dataset/upload HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 16:56:12,381] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 16:56:12] "POST /dataset/upload HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 16:56:15,892] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 16:56:15] "POST /dataset/upload HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-12-09 16:56:18,545] INFO _log() L224  127.0.0.1 - - [09/Dec/2023 16:56:18] "POST /dataset/upload HTTP/1.1" 200 - - call_trace=C:\Users\biaoz\OneDrive\Documentos\mvp-oscar-dataset\env\lib\site-packages\werkzeug\_internal.py L224 
